# paths are relative to auto_annotations

greedy_gpt4 : # gpt-4-0314_pairwise_vH_b5_chatml-prompt
  prompt_templates:
    with_inputs: "greedy_gpt4/chatml_b5_with_inputs.txt"
    without_inputs: "greedy_gpt4/chatml_b5_without_inputs.txt"
  fn_decoder: "openai_completions"
  decoder_kwargs:
    model_name: "gpt-4-0314"
    max_tokens: 250
    temperature: 0
  outputs_to_match:
    1: 'Output \(a'
    2: 'Output \(b'
  batch_size: 5
