ghost-8b-beta-disl-0x5:
  prompt_template: 'ghost-8b-beta-disl-0x5/prompt.txt'
  fn_completions: 'huggingface_local_completions'
  completions_kwargs:
    model_name: 'lamhieu/ghost-8b-beta-disl-0x5'
    model_kwargs:
      torch_dtype: 'bfloat16'
      attn_implementation: 'flash_attention_2'
      device_map: 'cuda'
    max_new_tokens: 2048
    temperature: 0.2
    top_p: 0.95
    do_sample: True
    batch_size: 16
  pretty_name: 'Ghost 8B Beta (d0x5)'
  link: 'https://huggingface.co/lamhieu/ghost-8b-beta-disl-0x5'
