Meta-Llama-3.1-8B-Instruct-Turbo:
  prompt_template: "Mixtral-8x7B-Instruct-v0.1/togetherai_prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo"
    max_tokens: 4096
    requires_chatml: True
    client_kwargs:
      base_url: 'https://api.together.xyz'
  pretty_name: "Llama 3.1 8B Instruct"
  link: "https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct"

